sudo: false
language: cpp

jobs:
  include:
  - name: Windows
    os: windows
    python: 3.8
    before_install:
      - choco install python --version=3.8.2
      - export PATH="/c/Python38:/c/Python38/Scripts:$PATH"
      - choco install -y visualstudio2022buildtools --package-parameters "--add Microsoft.VisualStudio.Component.VC.Tools.x86.x64"
    before_script:
      - cd ..
      - git clone --depth=1 --branch=1.10-dev --recursive https://github.com/alliedmodders/sourcemod sourcemod-1.10
      - git clone --depth=1 --branch=master https://github.com/alliedmodders/ambuild
      - cd ambuild
      - python setup.py install
      - cd %APPVEYOR_BUILD_FOLDER%
      - '"C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Auxiliary\Build\vcvarsall.bat"'
      - breakpad.bat
      - set PATH=%PATH%;%CD%\breakpad\src\src\tools\windows\dump_syms\Release
    script:
      - mkdir build
      - cd build
      - python ..\configure.py --enable-optimize
      - python build.py
  - name: Linux
    dist: bionic
    python: 3.8
    addons:
      apt:
        sources:
          - sourceline: 'deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-10 main'
            key_url: https://apt.llvm.org/llvm-snapshot.gpg.key
        packages:
          - clang-10
    compiler:
      - clang
    env:
      - CC=clang-10
      - CXX=clang++-10
    before_script:
      - cd ..
      - git clone --depth=1 --branch=1.10-dev --recursive https://github.com/alliedmodders/sourcemod sourcemod-1.10
      - git clone --depth=1 --branch=master --recursive https://github.com/alliedmodders/ambuild
      - cd ambuild && python setup.py install --user
      - cd $TRAVIS_BUILD_DIR
      - git fetch --unshallow || true
      - ./breakpad.sh && export PATH=$PATH:$PWD/breakpad/build/src/tools/linux/dump_syms/
    script:
      - mkdir build && cd build
      - python ../configure.py --enable-optimize
      - python ./build.py
